### ISSUE TITLE
Change default inline marker from #→ to #=>

### ISSUE THREAD

**Issue by aureliojargas** [aureliojargas/clitest#13]
At first it seemed a nice idea to use the Unicode arrow to identify the [special inline match mode](https://github.com/aureliojargas/clitest#alternative-syntax-inline-output), using `#→`. It is pretty and won't confuse with common commands.

```console
$ echo foo                    #→ foo
$ head /etc/passwd            #→ --lines 10
$ tac /etc/passwd | tac       #→ --file /etc/passwd
$ cat /etc/passwd             #→ --egrep ^root:
$ echo $((2 + 10))            #→ --regex ^\d+$
$ make test                   #→ --exit 0
$ pwd                         #→ --eval echo $PWD
```

The years passed, and now I find it annoying that I can't type that arrow directly in my keyboard. I always have to copy/paste from somewhere else. That's not a good user experience.

Recently, doing some tests with clitest in the [Alpine Linux docker image](https://hub.docker.com/_/alpine/), the Unicode char just didn't work in `/bin/ash`. Using any other ASCII-only marker was ok.

I'm inclined to change the default to the ASCII alternative `#=> `. It's uglier, but more portable and easier to type.

```console
$ echo foo                    #=> foo
$ head /etc/passwd            #=> --lines 10
$ tac /etc/passwd | tac       #=> --file /etc/passwd
$ cat /etc/passwd             #=> --egrep ^root:
$ echo $((2 + 10))            #=> --regex ^\d+$
$ make test                   #=> --exit 0
$ pwd                         #=> --eval echo $PWD
```

Since a default setting will change, this will break backward compatibility with previous versions and will require a new major version.

Current scripts who rely in the Unicode marker can just add a new option to continue using it without changing the test files (note the required space at the end):

```
clitest --inline-prefix '#→ ' tests.txt
```

Any thoughts on that?

**Comment by vmmello** [comment]
+1

Since the first time I used clitest I created a shell alias with `--inline-prefix` to workaround the annoyances of the Unicode character. I thought that you had chosen it because you had a quick way of typing it.

**Comment by kausdev** [comment]
+1

**Comment by gabriellhrn** [comment]
+1

The symbol is prettier but is annoying to type.
