### ISSUE TITLE
Multiline commands

### ISSUE THREAD

**Issue by marcioAlmada** [aureliojargas/clitest#30]
I'd like to run a command with a multiline string, but could not succeed:

Ex.:

This should store a multiline string into a variable:

```sh
$ MY_VAR='
{
    "error": {
        "messages": {
            "foo": "The parameter bar is out of range"
        }
    }
}
'
$
```

Proceed and use the variable...

```sh
$ echo "$MY_VAR"

{
    "error": {
        "messages": {
            "foo": "The parameter bar is out of range"
        }
    }
}

$
```
Currently I'm storing the assert string into a file, but most of the team prefer things inline. Perhaps we are doing multi line commands wrong or was this actually intended?

**Comment by aureliojargas** [comment]
@marcioAlmada Unfortunately, multiline commands are not supported. Supporting it would probably involve writing a mini shell parser to detect quoting, escaping, nesting, subshells, etc., and that's outside of the scope of this tool.

Using an external file is the alternative.

I'm sorry for taking so long to answer.
